### PR TITLE
Added details and logo for the BeeTogether guild

### PR DESCRIPTION
**Pull request by simeon4real**
BeeTogether is a new guild in the NEAR ecosystem that seeks to connect and support NGOs/NPO to blockchain via NEAR Protocol (climate neutral).

### CODE REVIEW

**Comment by simeon4real** [comment]
@mrdevri 1 check failed but there are no conflicts to the base branch.

**Comment by simeon4real** [comment]
no merge conflicts after pulling updates from upstream - not sure why test failed but all good from my end, @mrdevri

**Comment by simeon4real** [comment]
@mrdevri Good day, can you help check this PR?

**Comment by mrdevri** [comment]
Thanks for flagging @simeon4real, all set 👍

**Comment by simeon4real** [comment]
I appreciate it, @mrdevri.


QQ: Do guilds added to this ecosystem repo get added to https://near.org/guilds/? If yes, How long does it take?

**Pull request merged**
